#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/Knom.SKSPackage.Services/ && \
    dotnet build src/Knom.SKSPackage.Services/ && \
    echo "Now, run the following to start the project: dotnet run -p src/Knom.SKSPackage.Services/Knom.SKSPackage.Services.csproj --launch-profile web"
